config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :properties
  get 'home/index'
  devise_for :users,  controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/about_us', to: 'home#about_us'
  get '/legal_info', to: 'home#legal_info'

  root to: "home#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light bg-body-tertiary">
    <div class="container-fluid">
        <%= link_to 'GRUPO DDI', root_path, class: 'navbar-brand' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Inicio', home_index_path, class: 'nav-link' %>  
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Propiedades
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to 'Lista de propiedades', properties_path, class: 'nav-link'%></li>
                        <li><%= link_to 'Solicita tu pedido', new_order_path, class: 'nav-link'%></li>
                        <li><% if user_signed_in? %>
                            <li class="nav-item">
                                <%# <%= link_to 'Tus Reacciones', my_reactions_path, class: 'nav-link' %> 
                            </li>
                        <% end %>
                        </li>
                    </ul>  
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Acerca de 
                    </a>
                    <ul class="dropdown-menu">
                        <li><%= link_to 'Sobre nosotros', about_us_path, class: 'nav-link'%></li>
                        <li><%= link_to 'Información legal', legal_info_path, class: 'nav-link'%></li>
                    </ul>  
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <% if user_signed_in? %>
                    <% if current_user.name %>
                            Hola <%= current_user.name %>
                        <% else %>
                            Hola <%= current_user.email %>
                        <% end %>
                    <% else %>
                        Dale registrate o conectate
                    <% end %>
                    </a>
                    <ul class="dropdown-menu">
                        <% if user_signed_in? %>
                            <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                        <% else %>
                            <li><%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'%></li>
                        <% end %>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>